### ISSUE TITLE
Missing panel options in Blender 3.2.0

### ISSUE THREAD

**Issue by Ikkesett** [tkeskita/snappyhexmesh_gui#10]
After upgrading to Blender 3.2.0 some of the panel options does not appear in the top panel.
![bilde](https://user-images.githubusercontent.com/57672111/173873885-5fadead3-49b8-4a3b-bffd-91956133832e.png)
Running on Ubuntu 20.04.4 LTS

**Comment by Ikkesett** [comment]
Error found on line 288 in _init_.py:
_"Traceback (most recent call last):
  File "/home/openf/.config/blender/3.2/scripts/addons/snappyhexmesh_gui-master/__init__.py", line 288, in draw
    rowsub.prop(gui, "do_add_layers", text="", icon='HAIR')
TypeError: UILayout.prop(): error with keyword argument "icon" -  enum "HAIR" not found in ('NONE', 'QUESTION', 'ERROR', 'CANCEL', 'TRIA_RIGHT', 'TRIA_DOWN', 'TRIA_LEFT', 'TRIA_UP', 'ARROW_LEFTRIGHT', 'PLUS', 'DISCLOSURE_TRI_RIGHT', 'DISCLOSURE_TRI_DOWN', 'RADIOBUT_OFF', 'RADIOBUT_ON', 'MENU_PANEL', 'BLENDER', 'GRIP', 'DOT', 'COLLAPSEMENU', 'X', 'DUPLICATE', 'TRASH', 'COLLECTION_NEW"_

Works when icon type is changed.

**Comment by tkeskita** [comment]
Hi, thanks for the info, good to know there's once again icon name changes in upstream Blender! So, this needs to be fixed when upgrading the add-on for next Blender LTS version.

**Comment by DWTheo** [comment]
I also had this issue with Blender 3.4

For anyone wishing to attempt to fix this themselves the new icon name is "STRANDS"

so change __init__.py line 228 from:
`rowsub.prop(gui, "do_add_layers", text="", icon='HAIR')`
to:
`rowsub.prop(gui, "do_add_layers", text="", icon='STRANDS')`

**Comment by tkeskita** [comment]
note to self: `bpy.types.UILayout.bl_rna.functions["prop"].parameters["icon"].enum_items.keys()` lists available icon names

**Comment by tkeskita** [comment]
Thanks @DWTheo for digging up the new icon name! I added some checks to code, so that this kind of breaking is less likely in future. Now SnappyHexMeshGUI should work with all Blender LTS versions (and probably newer ones as well, although I haven't tested).
