### ISSUE TITLE
world in blockMeshDict

### ISSUE THREAD

**Issue by sudokit** [tkeskita/snappyhexmesh_gui#12]
Why does [snappyhexmesh_gui](https://github.com/tkeskita/snappyhexmesh_gui) add a world patch in blockMeshDict?
```
boundary
(
    world
    {
        type patch;
        faces
        (
            (3 7 6 2)
            (0 4 7 3)
            (2 6 5 1)
            (1 5 4 0)
            (0 3 2 1)
            (4 5 6 7)
        );
    }
)
```

**Comment by tkeskita** [comment]
Hi,
I think I took the template from some OpenFOAM tutorial which had this structure. AFAIK boundary patch needs to be named somehow. Looks like nowadays it's called `background`, previously I remember seeing `default` a lot, which is used in other places in another meaning also, so I ended up with `world`.

**Comment by sudokit** [comment]
Is it a thing i can just remove? Am trying to do some simulations and its always complaining that ```Cannot find patchField entry for world```

**Comment by sudokit** [comment]
What is it used for? Or like why is it needed?

**Comment by sudokit** [comment]
Never mind. Figured it out!

**Comment by sudokit** [comment]
Any idea why if i have no type empty geometry, the world isnt added but as soon as i have one empty type, it gets added?

**Comment by tkeskita** [comment]
No immediate ideas. Having `world` in the background mesh created by `blockMesh` should not be a problem, because the final mesh from  `snappyHexMesh` (assumedly you will only need that mesh) should not contain the `world` patch anymore.

If you need more help, please describe what you're trying to do in more detail. If you can, please share your blend file.

**Comment by sudokit** [comment]
Okay so. This is my run script:
```#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

runApplication blockMesh
runApplication surfaceFeatures
runApplication decomposePar
runParallel $application
runParallel checkMesh
runApplication reconstructParMes```

I am supposed to copy the constant/polyMesh folder to the case i want to use it in right? The polyMesh has a boundary file which contains a world patch which looks like this:
```
/*--------------------------------*- C++ -*----------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  10
     \\/     M anipulation  |
\*---------------------------------------------------------------------------*/
FoamFile
{
    format      ascii;
    class       polyBoundaryMesh;
    location    "constant/polyMesh";
    object      boundary;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

1
(
    world
    {
        type            patch;
        nFaces          17304;
        startFace       425292;
    }
)

// ************************************************************************* //
```
heres the blender file:
[CFDFluid.blend.zip](https://github.com/tkeskita/snappyhexmesh_gui/files/10550252/CFDFluid.blend.zip)

**Comment by tkeskita** [comment]
Hi,
you have "Enable Snapping" option disabled for the "walls" boundary. For a reason unknown to me, this causes snappyHexMesh volume boundary detection not to work correctly, and the mesh "leaks" to the world boundary. SnappyHexMesh seems to produce correct result if you enable "Enable Snapping".

BR,
Tuomo
