### ISSUE TITLE
Foam Fatal Error on DaveyGravey's tutorial 

### ISSUE THREAD

**Issue by roy-shuvashish** [tkeskita/snappyhexmesh_gui#13]
Hi, 
I am a beginner in blender and OpenFoam. I tried to follow the blender snappyhex addon tutorial by DaveyGravey but when I try to run the command  `mpirun -np 6 snappyHexMesh -parallel -overwrite `, it gives me a fatal error:
```
Shell wall does not support testing for inside
Probably it is not closed
```

 I have filled the inlet outlet correctly. Would you please tell me what's wrong I am doing? Here are my model files in my google drive:
[Link](https://drive.google.com/drive/folders/1P4rFkxmJknBWdfFffb0YgT9oHkEZuSAd?usp=sharing)
I highly appreciate your help. Thanks.

**Comment by tkeskita** [comment]
Can you please share the Blender file, the problem is there I assume.

**Comment by roy-shuvashish** [comment]
Thanks a lot for your reply. Here is the blender file for the tesla valve: [teslavalve blender file](https://drive.google.com/file/d/1BvLmdkTEJYiwRmhPA_KPyWtZgwiZ92-K/view?usp=sharing)

I have also tried to make a simple canal with an inlet, outlet and wall. I also faced the same problem. Here is the googel drive link with the blender file and also the exported dictionaries   [Canal_blender&_mesh_fiiles](https://drive.google.com/file/d/19J3QPpenzyiimVg_T5U89bx_SAgfZfeS/view?usp=sharing )  . Thanks a lot.

**Comment by tkeskita** [comment]
Hi,

I checked your teslavalve05.blend. I'm using openfoam.org v10 and it basically works for me. What OF variant and version are you using?

Your file does have an inconsistent setting for inlet and outlet objects: you have specified volume refinement, but these objects are just surfaces, so you should set Volume Refinement to None for them. I'm thinking maybe your OF variant detects this and gives that error? If volume refinement is used for an object, then that object must include surfaces which enclose a volume.

Side comment: The tesla valve geometry seems to be a bit broken, the mesh seems to be leaking inside the outer walls.

BR,
Tuomo

**Comment by roy-shuvashish** [comment]
Thank you so much for the solution. Removing the inlet, outlet inside Volume Refinement will solve the problem. I am also using a very old version of OF, it's actually blueCFD. 

Thanks.
-Shuvashish
