### ISSUE TITLE
Export only exports a single "world" Patch

### ISSUE THREAD

**Issue by c4tachan** [tkeskita/snappyhexmesh_gui#14]
When I intially started with snapyhexmesh_gui, I was able to get what looked like a low resolution mesh of my model into ParaView. In an attempt to improve the resolution, I modified some settings, but now the only mesh I'm getting is the world mesh "patch0"

I don't know what I've done wrong, and I have been unable to figure out how to fix it. I've attempted to use other models, like creating a new blender project and adding only the Monkey, then trying to export that, but I still only get the world mesh.

If I try to export a pair of cubes, I also still only get the world mesh.

What am I doing wrong? I have multiple STL files in the constant/trisurface/ directory.

**Comment by tkeskita** [comment]
Hi,
Export with default settings and only the Blender monkey mesh at origin should work.
Can you please share a Blender file?

**Comment by c4tachan** [comment]
Sure, I've been trying to return to default settings and I tried using the monkey file but that didn't work. Are the settings saved in a .blend file? (I'll get you a file that fails shortly)

**Comment by c4tachan** [comment]
Here's a .blend file that is giving me trouble: 
[MR-S.zip](https://github.com/tkeskita/snappyhexmesh_gui/files/11007201/MR-S.zip)

**Comment by c4tachan** [comment]
Actually, here's the entire FOAM folder that was exported and the results of `blockFoam` `surfaceFeatures` `snappyHexMesh` and `checkMesh` commands in the `output` folder.
[MR-S_for_bug_report.zip](https://github.com/tkeskita/snappyhexmesh_gui/files/11007212/MR-S_for_bug_report.zip)

**Comment by tkeskita** [comment]
Hi,
no need for including the OpenFOAM folder, the Blender file is enough and it contains all the settings. OK, so you seem to be preparing a mesh for an external flow study.
1. you need to add a mesh object which defines outer boundaries for the domain volume.
2. you need to Add Location In Mesh object if origin not inside the domain volume where mesh is to be generated.
3. the car mesh surfaces do not define a closed volume, therefore the mesh leaks inside the car.
I've now updated the docs, please check [the FAQ section](https://snappyhexmesh-gui.readthedocs.io/en/latest/snappy_gui.html#faq).

HTH,
Tuomo
