### ISSUE TITLE
How to Set Boundary Conditions in Bulk

### ISSUE THREAD

**Issue by liujiamingustc** [tkeskita/snappyhexmesh_gui#4]
Hello，when i import lots of parts into blender. I want to set a boundary condition that can be applied to all objects.But currently it seems to only be able to be set in sequence, it takes a lot of time.

**Comment by tkeskita** [comment]
Thanks for development idea. Currently only alternative is to merge several meshes into one object.

**Comment by liujiamingustc** [comment]
It is outstanding work!&nbsp;It greatly helps to improve the efficiency of multi region calculation!&nbsp;It would be great if you could batch set multiple objects. In addition, a large number of objects also need to set the corresponding boundary conditions and material properties, looking forward to further update.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tkeskita/snappyhexmesh_gui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 晚上8:32
收件人:&nbsp;"tkeskita/snappyhexmesh_gui"<snappyhexmesh_gui@noreply.github.com&gt;;
抄送:&nbsp;"刘佳明"<860407313@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tkeskita/snappyhexmesh_gui] How to Set Boundary Conditions in Bulk (#4)





 
Thanks for development idea. Currently only alternative is to merge several meshes into one object.

**Comment by tkeskita** [comment]
FYI I've now added Copy Settings to Objects operator (in Object Settings panel) which should do this.

**Comment by liujiamingustc** [comment]
> FYI I've now added Copy Settings to Objects operator (in Object Settings panel) which should do this.

Hi, there are some problem. If i use the chtMultiRegionFoam solver for multi-region CAD model with lots of  local contact surface in this CAD model part. How to set the conjugate boundary for this model?

**Comment by tkeskita** [comment]
I haven't used snappyHexMesh for chtMultiRegionFoam much, but I think the idea is to create cell zones in snappyHexMesh, then run `splitMeshRegions -cellZones` to separate zones into regions. So in snappyHexMeshGUI you must create meshes that surround the cells you want to have in each zone and then set `CellZoneType` to `inside` (or `outside`). I think splitMeshRegions should create the conjugate boundary automatically, but I'm not sure. Or did I misunderstand you question? Maybe you can share a small example picture?

**Comment by liujiamingustc** [comment]
> I haven't used snappyHexMesh for chtMultiRegionFoam much, but I think the idea is to create cell zones in snappyHexMesh, then run `splitMeshRegions -cellZones` to separate zones into regions. So in snappyHexMeshGUI you must create meshes that surround the cells you want to have in each zone and then set `CellZoneType` to `inside` (or `outside`). I think splitMeshRegions should create the conjugate boundary automatically, but I'm not sure. Or did I misunderstand you question? Maybe you can share a small example picture?


Thank you for your warm help, Your understand is right. 
![image](https://user-images.githubusercontent.com/21191982/102705385-324e1a00-42c2-11eb-8602-13e72c0c9e5f.png)
Here i get a simple picture to describe the problem. And i have run 'splitMeshRegions -cellZones' to separate zones into regions. But it report  'only a region Doing nothing.' In my case, four regions including a fluid and three solid was seted in snappyhexmesh-gui. Could you please tell me what is wrong in my case?

**Comment by tkeskita** [comment]
Please create a small example Blender file for that case (simple box geometry is OK), set up the snappyHexMeshGUI properties what you have tried for the case, save, and add blend file as attachment to this thread. I'll try to have a look.

**Comment by liujiamingustc** [comment]
> Please create a small example Blender file for that case (simple box geometry is OK), set up the snappyHexMeshGUI properties what you have tried for the case, save, and add blend file as attachment to this thread. I'll try to have a look.

Thank you for your help. I have solved the problem. Now, i plan to set the case.

**Comment by liujiamingustc** [comment]
> Please create a small example Blender file for that case (simple box geometry is OK), set up the snappyHexMeshGUI properties what you have tried for the case, save, and add blend file as attachment to this thread. I'll try to have a look.

Hello, there has a problem for blockmeshDict set. If there has a model with background mesh generated by blockmesh. How to set a larger region with smaller grid than model, but the region is less than background mesh. Looking forward to your reply.

**Comment by tkeskita** [comment]
Hi, you can refine inside or outside a volume bounded by a mesh object using Volume Refinement in [object settings panel](https://snappyhexmesh-gui.readthedocs.io/en/latest/snappy_gui.html#object-settings-panel). You must specify Volume Refinement Level.

PS. Would be interesting to know, did you need to do someting special to get conjugate boundaries working?

**Comment by liujiamingustc** [comment]
> Hi, you can refine inside or outside a volume bounded by a mesh object using Volume Refinement in [object settings panel](https://snappyhexmesh-gui.readthedocs.io/en/latest/snappy_gui.html#object-settings-panel). You must specify Volume Refinement Level.
> 
> PS. Would be interesting to know, did you need to do someting special to get conjugate boundaries working?

Thank you for your help, i just manually set the conjugate boundaries, but i have so much regions, the boundary setting and thermophysical properties of every region  will spend lots of time. And it is very error-prone. If there has function for conjugate boundary and thermophysical properties setting, it will provide a great deal of convenience in setting up the model.  Looking forward to further updates.

**Comment by liujiamingustc** [comment]
> Hi, you can refine inside or outside a volume bounded by a mesh object using Volume Refinement in [object settings panel](https://snappyhexmesh-gui.readthedocs.io/en/latest/snappy_gui.html#object-settings-panel). You must specify Volume Refinement Level.
> 
> PS. Would be interesting to know, did you need to do someting special to get conjugate boundaries working?

In addition: Due to a parallel mesh generation, if there has a regionProperties file in constant files, it will be more convenient for parallel grid generation .

**Comment by tkeskita** [comment]
I checked that I can produce a split multiregion mesh for the attached simple regionProperties file and domain with fluid, solid1 and solid2 regions in OpenFOAM 8 by running following commands (after running Export in SnappyHexMeshGUI). 
```
cp regionProperties constant/
blockMesh; surfaceFeatures; snappyHexMesh -overwrite
splitMeshRegions -cellZones -defaultRegionName fluid -overwrite
```

It automatically creates patches for the region boundaries, named like `fluid_to_solid1` and  `solid1_to_fluid` for all three regions, so the snappyHexMesh part seems to be working correctly. (Note to self: OpenFOAM chtMultiRegionFoam tutorial cases that use snappyHexMesh: `tutorials/heatTransfer/chtMultiRegionFoam/heatedDuct` and `shellAndTubeHeatExchanger`)

Now the toilsome part is to generate boundary specifications in the `/0` directory, which is your problem now if I understand correctly. Unfortunately this is outside the scope of this add-on, as it is only a GUI for snappyHexMesh, and not a preprocessor for chtMultiRegionFoam. However, if anyone out there wants to do it, I guess it should be possible to create a separate script which reads boundary files for each region and generates boundary settings using some defaults.

Attachment: [cht_test_001.zip](https://github.com/tkeskita/snappyhexmesh_gui/files/6015267/cht_test_001.zip)
