### ISSUE TITLE
Vessel example, not the same result, why?

### ISSUE THREAD

**Issue by j2l** [tkeskita/snappyhexmesh_gui#7]
Hello,

First of all thank you for this great addon!

I'm learning OpenFoam, please baer with me :)
I opened your example file, Exported the 8 objects.
Ran:
    blockMesh
    surfaceFeatures
    snappyHexMesh
    checkMesh
then paraFoam and got some blocky minecraft style Vessel only:
![image](https://user-images.githubusercontent.com/65325/121819211-226d2c80-cc8c-11eb-8e44-399e4aa7e6b1.png)
Any idea what's wrong?

**Comment by tkeskita** [comment]
Hi,
by default snappyHexMesh saves castellated mesh (seen in your picture) to time directory 1 and final mesh to time directory 2 or later. Go to last time point in Paraview to see final mesh.

**Comment by j2l** [comment]
Hello @tkeskita,

Thank you very much!
Indeed, I get the mesh:
![image](https://user-images.githubusercontent.com/65325/121942914-4f374780-cd51-11eb-8188-8c29bad588d8.png)
For future readers, to get the other parts:
- change opacity = 0.3, 
- untick internalMesh, 
- Apply
then you get all the parts to tick:
![image](https://user-images.githubusercontent.com/65325/121943489-ec927b80-cd51-11eb-8442-12bb7ce4b48e.png)

If there are other tricks, please let me know :)
