### ISSUE TITLE
Paraview question: can't get domain for aerodynamics

### ISSUE THREAD

**Issue by j2l** [tkeskita/snappyhexmesh_gui#8]
Hello,
I'm patiently learning this great plugin :smile: 
When I set my inlet, outlet to patches, and walls to wahtever, I don't get any of the domain parts visible in paraview:
![image](https://user-images.githubusercontent.com/65325/123520522-7119be00-d6b1-11eb-85fc-025aa5bb68ac.png)

What is the needed for an open domain parts?
Thanks

**Comment by tkeskita** [comment]
Hi, I think this is now related more to Paraview and OpenFOAM in general and not to snappyHexMeshGUI add-on. Please use another forum like [CFD-Online OpenFOAM or it's subforums](https://www.cfd-online.com/Forums/openfoam/) for general OpenFOAM questions, thanks!

**Comment by j2l** [comment]
Well, it was a question about snappyhexmesh_gui:
"When I set my inlet, outlet to patches, and walls to wahtever," ... in Blender.

**Comment by j2l** [comment]
I forgot the blend file.
[cadre regle profile.blend.zip](https://github.com/tkeskita/snappyhexmesh_gui/files/6721770/cadre.regle.profile.blend.zip)

**Comment by j2l** [comment]
I discovered your blockMesh and made it work.
I hope I can mix blockMesh and snappyhexmesh_gui.
Have a great day!
