### ISSUE TITLE
Which preprocessor is known to work fine with this addon export?

### ISSUE THREAD

**Issue by j2l** [tkeskita/snappyhexmesh_gui#9]
Hello,
It's more a discussion than a bug :)
I noticed that this addon always only export "world" boundary, no inlet, outlet or walls, or did I miss something?
 

Could you please share which OpenFOAM preprocessor you use?
Thank you

**Comment by tkeskita** [comment]
Hi,
snappyHexMeshGUI only creates OpenFOAM folder structure and dictionary files for snappyHexMesh, nothing more. You need to run blockMesh, surfaceFeatures and snappyHexMesh afterwards to actually generate the final mesh. After creating the mesh, you need to copy the mesh to your actual simulation run case folder and prepare the simulation dictionary files.

BR,
Tuomo

**Comment by j2l** [comment]
Thanks @tkeskita 
I'm looking for an open source integrated solution combining blockMesh, mesh generation, case prep to generate the simulation, then run OpenFOAM and follow up convergence. Some exist but are getting old (Ubuntu 16 or 18, OpenFOAM 6, etc).

**Comment by tkeskita** [comment]
I haven't tested this, but there is [CfdOF for FreeCAD](https://forum.freecadweb.org/viewtopic.php?t=33492). There seems to be [a new release](https://forum.freecadweb.org/viewtopic.php?f=37&t=67877) for it.
